# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 20:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamreporter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('summary_submitted', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='report',
            old_name='summary_time',
            new_name='summary_send_time',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='send_time',
            new_name='survey_send_time',
        ),
        migrations.RemoveField(
            model_name='report',
            name='summary_submitted',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='date',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='report',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamreporter.Report'),
        ),
        migrations.AddField(
            model_name='survey',
            name='daily',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teamreporter.DailyReport'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set([('report', 'date')]),
        ),
    ]
