# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 17:20
from __future__ import unicode_literals

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teamreporter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(null=True),
        ),
    ]
