# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamreporter', '0002_report_recurrences'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
