# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 21:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamreporter', '0003_report_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='time',
        ),
        migrations.AddField(
            model_name='report',
            name='send_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
