# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamreporter', '0006_report_summary_submitted'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('survey', 'question')]),
        ),
    ]
