# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 12:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamreporter', '0002_auto_20160411_2312'),
        ('teamreporter', '0007_auto_20160410_1554'),
    ]

    operations = [
    ]
