# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamreporter', '0009_auto_20160412_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='summary_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
