# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamreporter', '0010_auto_20160412_1826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='uuid',
            new_name='id',
        ),
    ]
